/* Tunnel Scope — entirely local, read-only source landscape. */
(function(){
'use strict';
const C=ScopeCore, T=window.THREE, $=id=>document.getElementById(id), esc=C.escape;
const ORIGINAL_HTML='<!doctype html>\n'+document.documentElement.outerHTML;
let data=JSON.parse($('repo-data').textContent), tree, layout, selected=null, selectedPage=null, editorFile=null, tabs=[], editorLine=1;
let searchMode='files', searchResult=[], searchIndex=0, searchTimer, toastTimer, tour=null, recorder=null, recordingCanvas=null, recordStart=0;
const fileLines=f=>f._lines||(f._lines=C.lines(f.source||''));
const fileTokens=f=>{if(!f._tokens){const state={comment:false,triple:false};f._tokens=fileLines(f).map(l=>C.tokens(l,state));}return f._tokens;};
const cleanData=()=>JSON.stringify(data,(k,v)=>['node','id','rect'].includes(k)||k.startsWith('_')?undefined:v).replace(/</g,'\\u003c').replace(/\u2028/g,'\\u2028').replace(/\u2029/g,'\\u2029');
function toast(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,4200);}
function saveBlob(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),60000);}
const folderIcon='<svg viewBox="0 0 16 16"><path d="M1.5 4h5l1.5 2h6.5v7.5h-13zM1.5 4V2.5h5L8 4h6.5v2"/></svg>';
const cubeIcon='<svg viewBox="0 0 24 24"><path d="m3 7 9-5 9 5v10l-9 5-9-5Z M3 7l9 5 9-5 M12 12v10"/></svg>';

class Landscape {
 constructor(){
  this.canvas=$('scene');this.overlay=$('labels');this.ctx=this.overlay.getContext('2d');this.viewport=$('viewport');this.labels=true;this.mode='3d';this.height=.85;this.colorMode='module';this.textureCache=new Map();this.activeTextures=0;this.dirty=true;this.hover=null;this.fallback=false;this.anim=null;this.width=1;this.heightPx=1;
  try{
   if(!T)throw Error('Renderer bundle missing');
   this.renderer=new T.WebGLRenderer({canvas:this.canvas,antialias:true,alpha:false,preserveDrawingBuffer:true,powerPreference:'high-performance'});
   this.renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.75));this.renderer.setClearColor('#11171f');this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.toneMapping=T.NoToneMapping;
   this.scene=new T.Scene();this.scene.background=new T.Color('#11171f');
   this.camera=new T.PerspectiveCamera(38,1,.015,3000);this.camera.position.set(95,145,150);
   this.controls=new window.OrbitControls(this.camera,this.canvas);this.controls.enableDamping=true;this.controls.dampingFactor=.095;this.controls.screenSpacePanning=false;this.controls.minDistance=.5;this.controls.maxDistance=1000;this.controls.maxPolarAngle=Math.PI/2-.09;this.controls.zoomToCursor=true;this.controls.panSpeed=.8;this.controls.rotateSpeed=.55;
   this.controls.mouseButtons={LEFT:T.MOUSE.PAN,MIDDLE:T.MOUSE.DOLLY,RIGHT:T.MOUSE.ROTATE};this.controls.touches={ONE:T.TOUCH.PAN,TWO:T.TOUCH.DOLLY_ROTATE};
   this.controls.addEventListener('change',()=>this.dirty=true);
   this.scene.add(new T.AmbientLight('#d3e0ed',1.55));const sun=new T.DirectionalLight('#ffffff',2.0);sun.position.set(-75,160,80);this.scene.add(sun);const fill=new T.DirectionalLight('#8295ac',.5);fill.position.set(80,50,-60);this.scene.add(fill);
   this.root=new T.Group();this.scene.add(this.root);this.ray=new T.Raycaster();this.pointer=new T.Vector2();
   const grid=new T.GridHelper(600,120,'#263340','#1b2631');grid.position.y=-.25;grid.material.transparent=true;grid.material.opacity=.65;this.scene.add(grid);
   this.selection=new T.LineSegments(new T.EdgesGeometry(new T.BoxGeometry(1,1,1)),new T.LineBasicMaterial({color:'#d0f3d8',transparent:true,opacity:.95,depthTest:true}));this.selection.visible=false;this.selection.renderOrder=10;this.scene.add(this.selection);
   this.canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();toast('GPU 컨텍스트가 중단되었습니다. 복구를 기다리는 중입니다.');this.lost=true;});
   this.canvas.addEventListener('webglcontextrestored',()=>{this.lost=false;this.rebuild();toast('GPU 렌더러를 복구했습니다.');});
  }catch(e){console.warn('Using 2D software fallback:',e.message);this.enableFallback();}
  this.bind();new ResizeObserver(()=>this.resize()).observe(this.viewport);this.resize();
 }
 enableFallback(){this.fallback=true;this.mode='2d';const n=this.canvas.cloneNode();this.canvas.replaceWith(n);this.canvas=n;this.flatCtx=n.getContext('2d');this.flat={x:0,z:0,zoom:1};$('gl-fallback').hidden=false;this.setMode('2d',false);}
 bind(){
  let down=null;this.canvas.addEventListener('pointerdown',e=>{down={x:e.clientX,y:e.clientY,button:e.button};stopTour();this.anim=null;if(this.fallback){this.flatDown={x:e.clientX,y:e.clientY,tx:this.flat.x,tz:this.flat.z};this.canvas.setPointerCapture(e.pointerId);}});
  this.canvas.addEventListener('pointermove',e=>{if(this.fallback&&this.flatDown&&(e.buttons||e.pointerType==='touch')){const scale=this.flatScale();this.flat.x=this.flatDown.tx-(e.clientX-this.flatDown.x)/scale;this.flat.z=this.flatDown.tz-(e.clientY-this.flatDown.y)/scale;this.dirty=true;return;}if(e.buttons){$('tooltip').hidden=true;return;}this.onHover(e);});
  this.canvas.addEventListener('pointerup',e=>{this.flatDown=null;if(down&&down.button===0&&Math.hypot(e.clientX-down.x,e.clientY-down.y)<5){const hit=this.pick(e);if(hit){selectNode(hit.file.node,hit);this.viewport.focus({preventScroll:true});}}down=null;});
  this.canvas.addEventListener('pointercancel',()=>{down=null;this.flatDown=null;});
  this.canvas.addEventListener('pointerleave',()=>{$('tooltip').hidden=true;this.hover=null;});
  this.canvas.addEventListener('dblclick',e=>{const hit=this.pick(e);if(hit){selectNode(hit.file.node,hit);this.focus(hit,true);}});
  this.canvas.addEventListener('contextmenu',e=>e.preventDefault());
  this.canvas.addEventListener('wheel',e=>{stopTour();this.anim=null;if(this.fallback){e.preventDefault();this.flat.zoom=Math.max(.2,Math.min(150,this.flat.zoom*Math.exp(-e.deltaY*.0015)));this.dirty=true;}},{passive:false});
 }
 resize(){const r=this.viewport.getBoundingClientRect();this.width=Math.max(1,r.width);this.heightPx=Math.max(1,r.height);const dpr=Math.min(devicePixelRatio||1,1.75);this.overlay.width=Math.round(this.width*dpr);this.overlay.height=Math.round(this.heightPx*dpr);this.ctx.setTransform(dpr,0,0,dpr,0,0);if(this.fallback){this.canvas.width=this.overlay.width;this.canvas.height=this.overlay.height;this.flatCtx.setTransform(dpr,0,0,dpr,0,0);}else{this.renderer.setSize(this.width,this.heightPx,false);this.camera.aspect=this.width/this.heightPx;this.camera.updateProjectionMatrix();}this.dirty=true;}
 clear(){if(this.fallback)return;for(const [,v] of this.textureCache){v.texture.dispose();v.mesh.material.dispose();v.mesh.geometry.dispose();this.root.remove(v.mesh);}this.textureCache.clear();while(this.root.children.length){const m=this.root.children[0];this.root.remove(m);if(m.geometry)m.geometry.dispose();if(m.material){(Array.isArray(m.material)?m.material:[m.material]).forEach(x=>x.dispose());}}}
 elevation(pg){const f=pg.file;return this.mode==='2d'?.025:(.28+Math.log2(1+f.lines)*.36+(pg.section.nonblank/32)*.82)*this.height;}
 rebuild(){
  this.clear();if(this.fallback){this.dirty=true;return;}
  const pages=layout.pages,dummy=new T.Object3D(),color=new T.Color();
  const box=new T.BoxGeometry(1,1,1);const mat=new T.MeshStandardMaterial({roughness:.85,metalness:.1});
  this.mesh=new T.InstancedMesh(box,mat,pages.length);this.mesh.instanceMatrix.setUsage(T.DynamicDrawUsage);this.mesh.frustumCulled=false;
  this.plates=new T.InstancedMesh(new T.BoxGeometry(1,1,1),new T.MeshStandardMaterial({roughness:1}),layout.files.length);this.plates.frustumCulled=false;
  layout.files.forEach((f,i)=>{const r=f.rect;dummy.position.set(r.x+r.w/2,.018,r.z+r.d/2);dummy.scale.set(r.w,.065,r.d);dummy.rotation.set(0,0,0);dummy.updateMatrix();this.plates.setMatrixAt(i,dummy.matrix);color.set(C.color(f,this.colorMode)).multiplyScalar(.25);this.plates.setColorAt(i,color);});
  pages.forEach((p,i)=>{const h=this.elevation(p);p.y=h;dummy.position.set(p.x+p.w/2,h/2+.07,p.z+p.d/2);dummy.scale.set(p.w,Math.max(.025,h),p.d);dummy.rotation.set(0,0,0);dummy.updateMatrix();this.mesh.setMatrixAt(i,dummy.matrix);color.set(C.color(p.file,this.colorMode)).multiplyScalar(.46+Math.min(1,p.section.nonblank/32)*.20);this.mesh.setColorAt(i,color);});
  this.root.add(this.plates,this.mesh);
  const borders=[];const addRect=(r,y)=>{const x=r.x,z=r.z,w=r.w,d=r.d;borders.push(x,y,z,x+w,y,z,x+w,y,z,x+w,y,z+d,x+w,y,z+d,x,y,z+d,x,y,z+d,x,y,z);};
  layout.files.forEach(f=>addRect(f.rect,.09));const geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute(borders,3));this.root.add(new T.LineSegments(geo,new T.LineBasicMaterial({color:'#60717f',transparent:true,opacity:.48})));
  // Every mark follows an actual non-empty source line's indentation and length.
  let marks=0;for(const f of layout.files)marks+=f.nonblank;this.lineMesh=new T.InstancedMesh(new T.PlaneGeometry(1,1),new T.MeshBasicMaterial({transparent:true,opacity:.48,depthWrite:false,side:T.DoubleSide}),Math.max(1,marks));this.lineMesh.frustumCulled=false;
  let li=0;for(const p of pages){const lines=fileLines(p.file);for(let j=p.section.start-1;j<p.section.end;j++){const text=lines[j];if(!text||!text.trim())continue;const count=Math.max(1,p.section.end-p.section.start+1),step=p.d/(count+3),indent=Math.min(72,(text.match(/^\s*/)||[''])[0].replace(/\t/g,'    ').length),len=Math.min(120-indent,text.trimEnd().replace(/\t/g,'    ').length-indent);const lw=Math.max(.001,len/125*p.w*.92),xx=p.x+p.w*.04+indent/125*p.w*.92;dummy.position.set(xx+lw/2,p.y+.079,p.z+step*(j-(p.section.start-1)+2));dummy.rotation.set(-Math.PI/2,0,0);dummy.scale.set(lw,Math.max(.001,step*.23),1);dummy.updateMatrix();this.lineMesh.setMatrixAt(li,dummy.matrix);color.set(/^\s*(\/\/|#|\*)/.test(text)?'#728888':C.color(p.file,this.colorMode)).lerp(new T.Color('#d7e4da'),.28);this.lineMesh.setColorAt(li++,color);}}
  this.lineMesh.count=li;this.root.add(this.lineMesh);this.mesh.computeBoundingSphere();this.plates.computeBoundingSphere();this.dirty=true;this.updateSelection();
 }
 setMode(mode,move=true){this.mode=this.fallback?'2d':mode;for(const m of ['2d','3d']){$('view-'+m).classList.toggle('active',this.mode===m);$('view-'+m).setAttribute('aria-pressed',this.mode===m);}if(this.controls)this.controls.enableRotate=this.mode==='3d';if(layout){this.rebuild();if(move)this.focus(selectedPage||selected||tree.root,false);}}
 project(x,y,z){if(this.fallback){const s=this.flatScale();return {x:this.width/2+(x-this.flat.x)*s,y:this.heightPx/2+(z-this.flat.z)*s,z:0};}const v=new T.Vector3(x,y,z).project(this.camera);return{x:(v.x+1)*this.width/2,y:(1-v.y)*this.heightPx/2,z:v.z};}
 flatScale(){return Math.min(this.width/165,this.heightPx/130)*this.flat.zoom;}
 bounds(r,y=0){const pts=[this.project(r.x,y,r.z),this.project(r.x+r.w,y,r.z),this.project(r.x+r.w,y,r.z+r.d),this.project(r.x,y,r.z+r.d)];const xs=pts.map(p=>p.x),ys=pts.map(p=>p.y);return {x:Math.min(...xs),y:Math.min(...ys),w:Math.max(...xs)-Math.min(...xs),h:Math.max(...ys)-Math.min(...ys),visible:pts.every(p=>p.z>-1&&p.z<1),pts};}
 pick(e){const r=this.canvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;if(this.fallback){const s=this.flatScale(),xx=(x-this.width/2)/s+this.flat.x,zz=(y-this.heightPx/2)/s+this.flat.z;return layout.pages.find(p=>xx>=p.x&&xx<=p.x+p.w&&zz>=p.z&&zz<=p.z+p.d)||null;}if(!this.mesh)return null;this.pointer.set(x/this.width*2-1,-y/this.heightPx*2+1);this.ray.setFromCamera(this.pointer,this.camera);const hit=this.ray.intersectObject(this.mesh,false)[0];return hit?layout.pages[hit.instanceId]:null;}
 onHover(e){const hit=this.pick(e);this.hover=hit;if(!hit){$('tooltip').hidden=true;return;}const r=this.canvas.getBoundingClientRect();$('tooltip').innerHTML='<b>'+esc(hit.file.path.split('/').pop())+'</b>'+C.number(hit.file.lines)+' lines · '+C.bytes(hit.file.bytes)+'<br><small>'+esc(hit.section.name||hit.file.language)+' · L'+hit.section.start+'–'+hit.section.end+' · 더블클릭하여 확대</small>';$('tooltip').hidden=false;$('tooltip').style.left=Math.max(6,Math.min(this.width-325,e.clientX-r.left+16))+'px';$('tooltip').style.top=Math.max(6,Math.min(this.heightPx-96,e.clientY-r.top+16))+'px';}
 updateSelection(){if(this.fallback||!this.selection)return;if(!selected||selected===tree.root){this.selection.visible=false;return;}const pg=selectedPage,r=pg||selected.rect;let h=pg?this.elevation(pg):(selected.file?.lines?(.28+Math.log2(1+selected.file.lines)*.36+.82)*this.height:.2);if(this.mode==='2d')h=.05;this.selection.visible=true;this.selection.position.set(r.x+r.w/2,h/2+.08,r.z+r.d/2);this.selection.scale.set(r.w+.035,h+.045,r.d+.035);this.dirty=true;}
 focus(target,page=false){
  const r=target.file&&target.section?target:target.rect||target.file?.rect||tree.root.rect;const y=page?this.elevation(target):target.file?.lines?Math.log2(1+target.file.lines)*.25*this.height:0;
  if(this.fallback){this.flat.x=r.x+r.w/2;this.flat.z=r.z+r.d/2;const fit=Math.max(r.w/this.width,r.d/this.heightPx);this.flat.zoom=Math.min(180,1/(fit*Math.min(this.width/165,this.heightPx/130)*1.4));this.dirty=true;return;}
  let dist=Math.max(r.d,r.w/this.camera.aspect)/(2*Math.tan(this.camera.fov*Math.PI/360))*1.40;
  if(target===tree.root)dist=Math.max(180,dist*1.09);
  dist=Math.max(.8,dist);let direction=this.mode==='2d'?new T.Vector3(0,1,.0001):page?new T.Vector3(.04,1,.15):new T.Vector3(.47,.92,1);direction.normalize();
  const toTarget=new T.Vector3(r.x+r.w/2,y,r.z+r.d/2);const toPos=toTarget.clone().addScaledVector(direction,dist);
  const duration=matchMedia('(prefers-reduced-motion: reduce)').matches?1:page?1150:980;
  this.anim={start:performance.now(),duration,from:this.camera.position.clone(),to:toPos,fromTarget:this.controls.target.clone(),toTarget};this.dirty=true;
 }
 zoom(factor){if(this.fallback){this.flat.zoom=Math.min(200,Math.max(.15,this.flat.zoom/factor));this.dirty=true;return;}this.anim=null;const v=this.camera.position.clone().sub(this.controls.target).multiplyScalar(factor);v.clampLength(.5,1000);this.camera.position.copy(this.controls.target).add(v);this.controls.update();this.dirty=true;}
 makeTexture(p){
  const cn=document.createElement('canvas');cn.width=1024;cn.height=896;const ctx=cn.getContext('2d');ctx.fillStyle='#142027';ctx.fillRect(0,0,cn.width,cn.height);
  ctx.strokeStyle=C.color(p.file,this.colorMode);ctx.lineWidth=3;ctx.strokeRect(1.5,1.5,1021,893);ctx.fillStyle='#bcdacb';ctx.font='18px monospace';ctx.fillText(p.file.path.split('/').pop()+'   L'+p.section.start+'–'+p.section.end,23,32);
  ctx.fillStyle='#25363e';ctx.fillRect(18,46,986,1);ctx.font='15px monospace';const toks=fileTokens(p.file),colors={comment:'#68868b',string:'#b8c998',number:'#d5b28b',keyword:'#c5a9d6',type:'#a2c7cc',fn:'#dbcca2',annotation:'#99b8d2','':'#b5c7d1'};
  for(let i=p.section.start-1;i<p.section.end;i++){const y=74+(i-p.section.start+1)*24.5;ctx.fillStyle='#557481';ctx.textAlign='right';ctx.fillText(String(i+1),57,y);ctx.textAlign='left';let x=75;for(const t of toks[i]||[]){ctx.fillStyle=colors[t.type];const tx=t.text.replace(/\t/g,'    ');ctx.fillText(tx,x,y);x+=ctx.measureText(tx).width;if(x>1020)break;}}
  const texture=new T.CanvasTexture(cn);texture.colorSpace=T.SRGBColorSpace;texture.anisotropy=Math.min(4,this.renderer.capabilities.getMaxAnisotropy());const mesh=new T.Mesh(new T.PlaneGeometry(p.w,p.d),new T.MeshBasicMaterial({map:texture,side:T.DoubleSide,polygonOffset:true,polygonOffsetFactor:-1,polygonOffsetUnits:-1}));mesh.rotation.x=-Math.PI/2;mesh.position.set(p.x+p.w/2,p.y+.092,p.z+p.d/2);mesh.renderOrder=2;this.root.add(mesh);return {texture,mesh,last:performance.now(),page:p};
 }
 updateLOD(){
  if(this.fallback)return;this.camera.updateMatrixWorld();const candidates=[];for(const p of layout.pages){if(p.file.binary||!p.section.start)continue;const b=this.bounds(p,p.y+.1);if(!b.visible||b.x+b.w<0||b.x>this.width||b.y+b.h<0||b.y>this.heightPx)continue;if(b.w>105&&b.h>90)candidates.push({p,b,area:b.w*b.h});}
  candidates.sort((a,b)=>(b.p===selectedPage)-(a.p===selectedPage)||b.area-a.area);const wanted=new Set(candidates.slice(0,28).map(c=>c.p.id));for(const [id,v] of this.textureCache)v.mesh.visible=wanted.has(id);
  let made=0;for(const c of candidates.slice(0,28)){const p=c.p;if(!this.textureCache.has(p.id)){if(made>=2)continue;this.textureCache.set(p.id,this.makeTexture(p));made++;}const v=this.textureCache.get(p.id);v.last=performance.now();v.mesh.visible=true;}
  while(this.textureCache.size>42){const ev=[...this.textureCache].filter(([id])=>!wanted.has(id)).sort((a,b)=>a[1].last-b[1].last)[0];if(!ev)break;const [id,v]=ev;this.root.remove(v.mesh);v.texture.dispose();v.mesh.geometry.dispose();v.mesh.material.dispose();this.textureCache.delete(id);}
  const active=[...this.textureCache.values()].filter(v=>v.mesh.visible).length;if(active!==this.activeTextures||made)this.dirty=true;this.activeTextures=active;this._lodPending=candidates.slice(0,28).some(c=>!this.textureCache.has(c.p.id));$('viewport').classList.toggle('source-lod',active>0);
 }
 drawLabels(){
  const c=this.ctx,w=this.width,h=this.heightPx;c.clearRect(0,0,w,h);if(!this.labels)return;const occupied=[];
  const label=(text,x,y,maxWidth,accent=false)=>{if(!Number.isFinite(x)||x<-80||x>w+20||y<7||y>h-15)return;c.font=(accent?'600 11px':'10px')+' ui-monospace,monospace';const original=text;let width=c.measureText(text).width;const limit=Math.max(30,Math.min(190,maxWidth));while(width>limit&&text.length>7){text=text.slice(0,-2);width=c.measureText(text+'…').width;}if(width>limit)return;if(text!==original)text+='…';const box={x:x-4,y:y-12,w:width+10,h:19};if(occupied.some(b=>box.x<b.x+b.w&&box.x+box.w>b.x&&box.y<b.y+b.h&&box.y+box.h>b.y))return;occupied.push(box);c.fillStyle=accent?'#15231feb':'#141d25dc';c.fillRect(box.x,box.y,box.w,box.h);c.fillStyle=accent?'#d2e8d7':'#b5c7ce';c.fillText(text,x,y);};
  const ordered=layout.files.slice().sort((a,b)=>b.lines-a.lines);
  if(selected&&selected.file){const f=selected.file,b=this.bounds(f.rect,(Math.log2(f.lines+1)*.36+.4)*this.height);label(f.path.split('/').pop(),b.x+5,b.y+14,Math.max(100,b.w),true);}
  for(const f of ordered){const r=f.rect,p=layout.pages.find(p=>p.file===f);const b=this.bounds(r,p?p.y+.1:0);if(!b.visible||b.w<40||b.h<18)continue;if(f===selected?.file)continue;const pos=this.project(r.x+.3,p?p.y+.1:0,r.z+.3);if(b.w>70&&b.h>28)label(f.path.split('/').pop(),pos.x+3,pos.y+10,Math.max(42,b.w*.9));}
  // Directory labels appear only for substantial disjoint regions; not duplicated chains.
  for(const n of layout.dirs){if(!n.path||n.children.length===1||n.count<3)continue;const b=this.bounds(n.rect,.15);if(b.visible&&b.w>160&&b.h>90){const p=this.project(n.rect.x+.3,.15,n.rect.z+.3);label(n.path.split('/').slice(-2).join('/'),p.x,p.y-3,b.w,true);}}
 }
 drawMini(){const canvas=$('minimap'),c=canvas.getContext('2d'),w=canvas.width,h=canvas.height;c.clearRect(0,0,w,h);c.fillStyle='#111b24';c.fillRect(0,0,w,h);const s=Math.min((w-8)/layout.width,(h-8)/layout.depth),ox=(w-layout.width*s)/2,oz=(h-layout.depth*s)/2;for(const f of layout.files){const r=f.rect;c.fillStyle=C.color(f,this.colorMode);c.globalAlpha=f===selected?.file?1:.5;c.fillRect(ox+(r.x+layout.width/2)*s,oz+(r.z+layout.depth/2)*s,Math.max(.8,r.w*s-.7),Math.max(.8,r.d*s-.7));}c.globalAlpha=1;let x=0,z=0,dist=150;if(this.fallback){x=this.flat.x;z=this.flat.z;dist=80/this.flat.zoom;}else{x=this.controls.target.x;z=this.controls.target.z;dist=this.camera.position.distanceTo(this.controls.target)*.25;}const cx=ox+(x+layout.width/2)*s,cy=oz+(z+layout.depth/2)*s;c.strokeStyle='#d1f1d3';c.lineWidth=1.3;c.strokeRect(cx-dist*s/2,cy-dist*s*.36,dist*s,dist*s*.72);c.fillStyle='#f0fff0';c.fillRect(cx-2,cy-2,4,4);}
 drawAxes(){const cn=$('axes'),c=cn.getContext('2d');c.clearRect(0,0,84,84);const axes=[['X',[1,0,0],'#b89089'],['Y',[0,1,0],'#90bda5'],['Z',[0,0,1],'#8da8c7']];for(const [name,a,col] of axes){let x=a[0],y=-a[2];if(!this.fallback){const v=new T.Vector3(...a).applyQuaternion(this.camera.quaternion.clone().invert());x=v.x;y=-v.y;}c.strokeStyle=col;c.fillStyle=col;c.beginPath();c.moveTo(40,42);c.lineTo(40+x*23,42+y*23);c.stroke();c.font='9px monospace';c.fillText(name,37+x*32,45+y*32);}c.fillStyle='#71818c';c.beginPath();c.arc(40,42,2,0,Math.PI*2);c.fill();}
 renderFlat(){const c=this.flatCtx,w=this.width,h=this.heightPx;c.fillStyle='#11171f';c.fillRect(0,0,w,h);for(const p of layout.pages){const b=this.bounds(p);if(b.x+b.w<0||b.x>w||b.y+b.h<0||b.y>h)continue;c.fillStyle=C.color(p.file,this.colorMode);c.globalAlpha=.6;c.fillRect(b.x,b.y,Math.max(.5,b.w-.5),Math.max(.5,b.h-.5));c.globalAlpha=1;if(b.w>140&&b.h>110){c.save();c.beginPath();c.rect(b.x,b.y,b.w,b.h);c.clip();c.fillStyle='#152027';c.fillRect(b.x+1,b.y+1,b.w-2,b.h-2);c.font='10px monospace';c.fillStyle='#bfddce';fileLines(p.file).slice(p.section.start-1,p.section.end).forEach((l,i)=>c.fillText(l,b.x+6,b.y+13+i*12));c.restore();}}if(selected&&selected.rect){const b=this.bounds(selectedPage||selected.rect);c.strokeStyle='#d1f1d3';c.strokeRect(b.x,b.y,b.w,b.h);}}
 tick(now){if(!layout||this.lost)return;if(this.anim&&!this.fallback){const a=this.anim,t=Math.min(1,(now-a.start)/a.duration),e=t<.5?4*t*t*t:1-Math.pow(-2*t+2,3)/2;this.camera.position.lerpVectors(a.from,a.to,e);this.controls.target.lerpVectors(a.fromTarget,a.toTarget,e);if(t===1)this.anim=null;this.dirty=true;}if(this.controls)this.controls.update();if(!this.dirty&&!this.anim&&!this._lodPending)return false;if(this.fallback){this.renderFlat();}else{if(!this._lodTime||now-this._lodTime>100){this.updateLOD();this._lodTime=now;}this.renderer.render(this.scene,this.camera);}this.drawLabels();if(!this._miniTime||now-this._miniTime>120){this.drawMini();this.drawAxes();this._miniTime=now;}this.dirty=false;return true;}
}
let view;
const expanded=new Set(['','app','app/src','app/src/main','app/src/main/java','app/src/main/java/com','app/src/main/java/com/tunnelvpn','app/src/main/java/com/tunnelvpn/app']);
function initData(next){
 data=next;tree=C.tree(data.files);layout=C.layout(tree,$('metric').value);tree.root.name=data.repo.split('/').pop();selected=tree.root;selectedPage=null;editorFile=null;tabs=[];closeEditor();
 $('brand').querySelector('.project').textContent=tree.root.name;$('map-heading').querySelector('h1').innerHTML=esc(tree.root.name)+'<span class="heading-suffix">.scope</span>';$('map-heading').querySelector('.eyebrow').textContent=(data.repo.includes('/')?data.repo.split('/')[0]:'LOCAL')+' / CODEBASE';
 $('commit-label').textContent=data.worktree?'local':data.commit.slice(0,7);$('snapshot-date').textContent=data.worktree?'로컬 폴더 · 읽기 전용':data.commitDate.slice(0,10)+' · '+data.commit.slice(0,7);
 $('map-stats').innerHTML='<b>'+C.number(data.metrics.files)+'</b> files&nbsp; /&nbsp; <b>'+C.number(data.metrics.lines)+'</b> lines&nbsp; /&nbsp; <b>'+C.bytes(data.metrics.bytes)+'</b>';
 renderTree();renderInspector();renderBreadcrumbs();renderLegend();renderAbout();if(view){view.rebuild();view.focus(tree.root);}
}
function renderTree(){
 const q=$('tree-filter').value.trim().toLowerCase(),out=[];
 const relevant=n=>n.path.toLowerCase().includes(q)||(!n.file&&n.children.some(relevant));
 function row(n,depth){if(q&&!relevant(n))return;let label=n.name||tree.root.name,target=n;if(!n.file&&n.path){while(target.children.length===1&&!target.children[0].file){target=target.children[0];label+='/'+target.name;}}
  const open=q||expanded.has(n.path)||expanded.has(target.path),sel=selected===n||selected===target;
  out.push('<button class="tree-row'+(sel?' selected':'')+'" role="treeitem" '+(!n.file?'aria-expanded="'+!!open+'"':'')+' aria-selected="'+sel+'" data-tree="'+esc(target.path)+'" style="padding-left:'+(10+depth*12)+'px" title="'+esc(target.path||tree.root.name)+'"><span class="arrow">'+(n.file?'':open?'⌄':'›')+'</span>'+(n.file?'<span class="file-dot" style="color:'+C.color(n.file,'language')+'">'+esc(n.file.binary?'◻':n.file.language==='Kotlin'?'Kt':n.file.language.slice(0,2))+'</span>':folderIcon)+'<span class="tree-name">'+esc(label)+'</span><span class="tree-count">'+(n.file?'':target.count)+'</span></button>');
  if(!n.file&&open)target.children.forEach(c=>row(c,depth+1));
 }row(tree.root,0);$('tree').innerHTML=out.join('')||'<p class="empty-note">일치하는 경로가 없습니다.</p>';
}
function selectNode(n,page=null){selected=n||tree.root;selectedPage=page;view?.updateSelection();renderInspector();renderBreadcrumbs();renderTree();$('status-file').textContent=selected.path||'전체 저장소';}
function renderBreadcrumbs(){const parts=(selected?.path||'').split('/').filter(Boolean);let path='';$('breadcrumbs').innerHTML='<button data-path="">'+esc(tree.root.name)+'</button>'+parts.map(p=>{path+=(path?'/':'')+p;return '<span class="crumb-sep">/</span><button data-path="'+esc(path)+'">'+esc(p)+'</button>';}).join('');$('breadcrumbs').scrollLeft=$('breadcrumbs').scrollWidth;}
function renderInspector(){
 const n=selected||tree.root,f=n.file,isRoot=n===tree.root;const subset=f?[f]:data.files.filter(f=>!n.path||f.path.startsWith(n.path+'/'));const bytes=n.bytes,lines=n.lines,count=n.count;
 $('selection-kind').textContent=f?'FILE':isRoot?'REPOSITORY':'DIRECTORY';let html='<div class="inspector-icon">'+(f?esc(f.binary?'BIN':f.language==='Kotlin'?'Kt':f.language.slice(0,2)):cubeIcon)+'</div><div class="inspector-name">'+esc(n.name||tree.root.name)+'</div><div class="inspector-path">'+esc(n.path||data.repo)+'</div>';
 html+='<div class="metric-cards"><div class="metric-card"><b>'+C.number(lines)+'</b><span>텍스트 줄 수</span></div><div class="metric-card"><b>'+(f?C.bytes(bytes):C.number(count))+'</b><span>'+(f?'파일 크기':'실제 파일')+'</span></div><div class="metric-card"><b>'+C.number(n.symbols)+'</b><span>추출된 선언</span></div><div class="metric-card"><b>'+(f?f.sections.length:C.bytes(bytes))+'</b><span>'+(f?'소스 페이지':'전체 크기')+'</span></div></div>';
 html+='<p class="metric-note">공백·주석을 포함한 물리적 줄 수입니다. 작은 블록 하나는 연속된 최대 32줄입니다.</p>';
 if(f){html+='<button class="source-open" data-open-source="'+f.id+'" '+(f.binary?'disabled':'')+'>'+(f.binary?'바이너리 · 텍스트 없음':'원본 소스 열기')+'<kbd>Enter</kbd></button>';
  if(selectedPage&&selectedPage.section.start)html+='<div class="selection-line">선택된 페이지 <b>L'+selectedPage.section.start+'–'+selectedPage.section.end+'</b></div>';
  html+='<div class="hash-row"><span>GIT BLOB SHA-1</span><code>'+esc(f.sha||'로컬 파일 · 미계산')+'</code></div>';
  html+='<div class="inspector-section"><h3>SYMBOLS <span>'+f.symbols.length+'</span></h3><p class="metric-note">선언 패턴 인덱스 · AST 분석 아님</p>';
  html+=f.symbols.slice(0,180).map(s=>'<button class="symbol-button" data-symbol="'+s.line+'"><span class="symkind">'+esc(s.kind==='fun'?'fn':s.kind.slice(0,2))+'</span><span class="symname">'+esc(s.name)+'</span><small>'+s.line+'</small></button>').join('')||'<p class="empty-note">인식된 선언이 없습니다.</p>';
  if(f.symbols.length>180)html+='<p class="metric-note">180개 표시 · 전체 심볼은 검색에서 확인</p>';html+='</div>';
  if(!data.worktree)html+='<a class="inspect-link" href="https://github.com/'+encodeURI(data.repo)+'/blob/'+data.commit+'/'+f.path.split('/').map(encodeURIComponent).join('/')+'" target="_blank" rel="noopener noreferrer">GitHub에서 이 커밋 보기 ↗</a>';
 }else{
  const langs=new Map();subset.forEach(f=>langs.set(f.language,(langs.get(f.language)||0)+f.lines));const list=[...langs].sort((a,b)=>b[1]-a[1]);html+='<div class="inspector-section"><h3>LANGUAGES <span>줄 수 기준</span></h3><div class="language-bar">'+list.filter(x=>x[1]).map(([l,v])=>'<span style="width:'+(v/Math.max(1,lines)*100)+'%;background:'+C.languageColors[l]+'"></span>').join('')+'</div>'+list.slice(0,6).map(([l,v])=>'<div class="language-item"><i style="background:'+C.languageColors[l]+'"></i><span>'+esc(l)+'</span><b>'+C.number(v)+'</b></div>').join('')+'</div>';
  html+='<div class="inspector-section"><h3>LARGEST FILES <span>줄 수</span></h3>'+subset.slice().sort((a,b)=>b.lines-a.lines).slice(0,8).map((f,i)=>'<button class="largest-file" data-file="'+f.id+'"><span class="rank">'+String(i+1).padStart(2,'0')+'</span><span>'+esc(f.path.split('/').pop())+'</span><small>'+C.number(f.lines)+'</small></button>').join('')+'</div>';
  html+='<p class="metric-note">면적: '+({'lines':'파일의 물리적 줄 수','bytes':'파일의 실제 바이트 수','equal':'파일마다 동일한 면적'}[$('metric').value])+'<br>높이: 파일 줄 수의 로그값 + 페이지의 비어 있지 않은 줄 비율.<br>빈 파일과 바이너리에는 선택 가능한 최소 면적을 부여합니다.</p>';
 }$('inspector-body').innerHTML=html;
}
function renderLegend(){let items;if(view?.colorMode==='language'){const m=new Map();data.files.forEach(f=>m.set(f.language,(m.get(f.language)||0)+1));items=[...m].sort((a,b)=>b[1]-a[1]).slice(0,6).map(([l,n])=>[l,n,C.languageColors[l]||'#8a999f']);}else if(view?.colorMode==='size'){items=[['smaller',null,'#729dab'],['larger',null,'#c7a08a']];}else{items=Object.entries(C.palette).map(([l,c])=>[l,data.files.filter(f=>C.module(f.path)===l).length,c]).filter(x=>x[1]);}$('legend').innerHTML=items.map(([l,n,c])=>'<div class="legend-row"><span style="background:'+c+'"></span><span>'+esc(l)+'</span>'+(n!==null?'<small>'+n+'</small>':'')+'</div>').join('');}
function renderAbout(){const license=data.files.find(f=>f.path==='LICENSE');$('about-content').innerHTML='<div class="about-row"><span>REPOSITORY</span>'+esc(data.repo)+'</div><div class="about-row"><span>COMMIT / SOURCE IDENTITY</span><code>'+esc(data.commit)+'</code><br>'+esc(data.worktree?'로컬 작업 디렉터리. HEAD와 내용이 다를 수 있습니다.':data.commitDate+' · 원본 커밋 고정 스냅샷')+'</div><div class="about-row"><span>INTEGRITY</span>'+C.number(data.metrics.textFiles)+'개 텍스트 원문 전체 내장. 빌드 시 원문 바이트로 Git blob SHA-1을 재계산합니다. 바이너리 '+(data.metrics.files-data.metrics.textFiles)+'개는 지도에 메타데이터만 표시합니다. 원본 코드와 웹 페이지는 실행하지 않습니다.</div><div class="about-row"><span>METRICS</span>'+C.number(data.metrics.lines)+' physical lines · '+C.number(data.metrics.nonblank)+' nonblank lines · '+C.number(data.metrics.pages)+' source pages. 심볼은 주석·문자열을 제외한 선언 패턴으로 추출한 탐색용 인덱스입니다. 완전한 AST 또는 호출 그래프가 아닙니다.</div><div class="about-row"><span>PRIVACY</span>CDN · 폰트 요청 · 분석 서버 · 원격 텔레메트리 없음. 코드 검색·가져오기·저장은 기기 안에서 수행됩니다. 외부 링크를 직접 누른 경우에만 브라우저가 GitHub를 엽니다.</div><div class="about-row"><span>RENDERER</span>Tunnel Scope 1.0 · Three.js r170 + OrbitControls (MIT). Instanced geometry · source-text LOD · 가상화된 소스 뷰어. 성능은 GPU·브라우저·화면 해상도에 따라 달라집니다.</div>'+(license?'<h3>원본 저장소 라이선스</h3><pre class="about-license">'+esc(license.source)+'</pre>':'')+'<h3>Three.js</h3><pre class="about-license">The MIT License\n\nCopyright © 2010-2024 three.js authors\n\nPermission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:\n\nThe above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.\n\nTHE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.</pre>';}
function openEditor(f,line=1){if(!f||f.binary){toast('바이너리에는 텍스트 소스가 없습니다.');return;}editorFile=f;editorLine=Math.min(Math.max(1,line),Math.max(1,f.lines));if(!tabs.includes(f))tabs.push(f);if(tabs.length>8)tabs.shift();$('editor').hidden=false;document.body.classList.add('editor-open');$('editor-tabs').innerHTML=tabs.map(t=>'<button class="'+(t===f?'active':'')+'" data-tab="'+t.id+'">'+esc(t.path.split('/').pop())+'</button>').join('');$('editor-path').textContent=f.path;$('editor-language').textContent=f.language+' · UTF-8';$('line-input').max=String(f.lines);$('line-input').value=String(editorLine);const ls=fileLines(f);$('source-spacer').style.height=Math.max(22,ls.length*22)+'px';let longest=0;for(const l of ls)longest=Math.max(longest,l.replace(/\t/g,'    ').length);$('source-spacer').style.width=Math.max(600,longest*7.3+100)+'px';fileTokens(f);$('source-scroll').scrollTop=Math.max(0,(editorLine-4)*22);renderSource();selectNode(f.node,layout.pages.find(p=>p.file===f&&p.section.start<=editorLine&&p.section.end>=editorLine)||null);}
function renderSource(){if(!editorFile||$('editor').hidden)return;const s=$('source-scroll'),ls=fileLines(editorFile),start=Math.max(0,Math.floor(s.scrollTop/22)-8),end=Math.min(ls.length,start+Math.ceil(s.clientHeight/22)+18);const tokens=fileTokens(editorFile);$('source-lines').style.top=start*22+'px';$('source-lines').innerHTML=ls.length?ls.slice(start,end).map((l,j)=>'<div class="source-line'+(start+j+1===editorLine?' highlight':'')+'"><span class="ln">'+(start+j+1)+'</span><code>'+C.tokenHTML(tokens[start+j])+'</code></div>').join(''):'<div class="source-line"><span class="ln">0</span><code>빈 파일</code></div>';$('editor-range').textContent=(ls.length?start+1:0)+'–'+end+' / '+C.number(ls.length)+' lines';}
function closeEditor(){$('editor').hidden=true;document.body.classList.remove('editor-open');}
function jumpSource(){if(!editorFile)return;const n=Math.max(1,Math.min(editorFile.lines,Number($('line-input').value)||1));editorLine=n;$('source-scroll').scrollTop=Math.max(0,(n-4)*22);renderSource();selectNode(editorFile.node,layout.pages.find(p=>p.file===editorFile&&p.section.start<=n&&p.section.end>=n));}
function openSearch(mode='files'){searchMode=mode;updateSearchTabs();$('search-dialog').showModal();$('search-input').focus();$('search-input').select();doSearch();}
function updateSearchTabs(){document.querySelectorAll('.search-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.mode===searchMode));$('search-input').placeholder=searchMode==='files'?'파일 이름 또는 경로…':searchMode==='symbols'?'함수 · 클래스 · 선언 검색…':'전체 원본 소스에서 검색…';}
function doSearch(){let q=$('search-input').value;if(q.startsWith('@')){q=q.slice(1);searchMode='symbols';updateSearchTabs();}const result=C.search(data.files,q,searchMode,250);searchResult=result.results;searchIndex=0;$('search-count').textContent=C.number(result.count)+(result.count>250?' · 250개 표시':'개');$('search-results').innerHTML=searchResult.length?searchResult.map((r,i)=>'<button class="search-result'+(i===0?' chosen':'')+'" data-result="'+i+'" role="option" aria-selected="'+(i===0)+'"><span class="sr-title"><span class="file-dot" style="color:'+C.color(r.f,'language')+'">'+esc(r.kind?'ƒ':r.f.language.slice(0,2))+'</span>'+C.highlight(r.title,q)+(r.line?'<span class="sr-line">L'+r.line+'</span>':'')+'</span><span class="sr-path">'+C.highlight(r.f.path,q)+'</span>'+(r.snippet!==undefined?'<span class="sr-snippet">'+C.highlight(r.snippet.slice(0,340),q)+'</span>':'')+'</button>').join(''):'<div class="search-empty">'+(searchMode==='text'&&!q?'검색할 코드나 문자열을 입력하세요.':'일치하는 결과가 없습니다.')+'</div>';}
function chooseSearch(index){clearTimeout(searchTimer);const r=searchResult[index];if(!r)return;$('search-dialog').close();selectNode(r.f.node);if(r.line){const p=layout.pages.find(p=>p.file===r.f&&p.section.start<=r.line&&p.section.end>=r.line);view.focus(p||r.f.node,!!p);openEditor(r.f,r.line);}else{view.focus(r.f.node);openEditor(r.f,1);}document.body.classList.remove('mobile-explorer');}
function startTour(){if(tour){stopTour();return;}closeEditor();const preferred=['TurboTcpForwarder.kt','TunnelVpnService.kt','DnsMessageValidator.kt','AegisLocal2Engine.kt','TurboAiEngine.kt'];const picks=preferred.map(name=>data.files.find(f=>f.path.endsWith('/'+name)&&!f.path.includes('/test/'))).filter(Boolean);if(!picks.length)picks.push(...data.files.filter(f=>f.lines>0).sort((a,b)=>b.lines-a.lines).slice(0,5));const stages=[{target:tree.root,label:'전체 저장소 · '+C.number(data.metrics.lines)+' lines',duration:4200}];for(const f of picks){stages.push({target:f.node,label:f.path.split('/').pop()+' · '+C.number(f.lines)+' lines',duration:3800});const sym=f.symbols.find(s=>s.kind==='fun'||s.kind==='method')||f.symbols[0];const pg=layout.pages.find(p=>p.file===f&&p.section.start<=(sym?.line||1)&&p.section.end>=(sym?.line||1));if(pg)stages.push({target:pg,page:true,label:(sym?.name||'SOURCE')+' · L'+pg.section.start+'–'+pg.section.end,duration:4500});}stages.push({target:tree.root,label:'Sp2ctr2 / '+tree.root.name,duration:4000});tour={stages,index:0,next:0};$('tour-btn').classList.add('active');$('tour-caption').hidden=false;}
function stopTour(){if(!tour)return;tour=null;$('tour-btn').classList.remove('active');$('tour-caption').hidden=true;}
function tickTour(now){if(!tour||now<tour.next)return;const s=tour.stages[tour.index++];if(!s){stopTour();return;}selectNode(s.target.file&&s.page?s.target.file.node:s.target,s.page?s.target:null);view.focus(s.target,!!s.page);$('tour-caption').textContent=s.label;tour.next=now+s.duration;}
function composite(canvas){const w=view.canvas.width,h=view.canvas.height;if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;}const c=canvas.getContext('2d');c.drawImage(view.canvas,0,0,w,h);c.drawImage(view.overlay,0,0,w,h);c.fillStyle='#10171fce';c.fillRect(0,h-42,w,42);c.fillStyle='#b6cec4';c.font='13px monospace';c.fillText(data.repo+'  /  '+data.commit.slice(0,12)+'  /  '+C.number(data.metrics.lines)+' physical lines',18,h-16);}
function capture(){view.dirty=true;view.tick(performance.now());const cn=document.createElement('canvas');composite(cn);cn.toBlob(b=>{if(b)saveBlob(b,tree.root.name+'-scope.png');else toast('이미지 저장에 실패했습니다.');},'image/png');}
function record(){if(recorder){recorder.stop();return;}if(typeof MediaRecorder==='undefined'||!HTMLCanvasElement.prototype.captureStream){toast('이 브라우저는 지도 녹화를 지원하지 않습니다. PNG 저장을 사용하세요.');return;}try{recordingCanvas=document.createElement('canvas');composite(recordingCanvas);const stream=recordingCanvas.captureStream(30);const mime=['video/webm;codecs=vp9','video/webm;codecs=vp8','video/webm','video/mp4'].find(t=>MediaRecorder.isTypeSupported(t));if(!mime)throw Error('지원되는 영상 코덱이 없습니다.');recorder=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:8000000});const chunks=[];recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};recorder.onstop=()=>{stream.getTracks().forEach(t=>t.stop());const blob=new Blob(chunks,{type:mime});saveBlob(blob,tree.root.name+'-scope.'+(mime.includes('mp4')?'mp4':'webm'));recorder=null;recordingCanvas=null;$('record-btn').classList.remove('recording');$('record-btn').title='지도 영상 녹화 / 종료';toast('실제 지도 영상을 저장했습니다.');};recorder.onerror=()=>toast('영상 인코더 오류: 녹화를 종료하고 다시 시도하세요.');recorder.start(500);recordStart=performance.now();$('record-btn').classList.add('recording');toast('녹화 중입니다. 투어 또는 직접 탐색 후 녹화 버튼을 다시 누르세요. 최대 120초.');}catch(e){recorder=null;recordingCanvas=null;toast('녹화 시작 실패: '+e.message);}}
function exportHTML(){const start=ORIGINAL_HTML.indexOf('<script id="repo-data"'),contentStart=ORIGINAL_HTML.indexOf('>',start)+1,end=ORIGINAL_HTML.indexOf('</script>',contentStart);const html=ORIGINAL_HTML.slice(0,contentStart)+cleanData()+ORIGINAL_HTML.slice(end);saveBlob(new Blob([html],{type:'text/html;charset=utf-8'}),tree.root.name+'_Scope.html');}
async function importFolder(list){if(!list?.length)return;const files=[...list],total=files.reduce((s,f)=>s+f.size,0);if(total>200*1024*1024){toast('선택한 폴더가 200 MiB를 초과합니다. 소스 하위 폴더를 선택하세요.');return;}stopTour();$('loading').hidden=false;const out=[],skip=new Set(['.git','node_modules','.gradle','build','dist','.idea','.venv','venv','__pycache__','target']);const name=files[0].webkitRelativePath?.split('/')[0]||'Local';let ignored=0;try{for(let i=0;i<files.length;i++){const file=files[i],parts=(file.webkitRelativePath||file.name).split('/');if(file.webkitRelativePath)parts.shift();if(parts.some(p=>skip.has(p))){ignored++;continue;}const path=parts.join('/');let source=null;if(file.size<=32*1024*1024){const raw=new Uint8Array(await file.arrayBuffer());try{if(!raw.includes(0))source=new TextDecoder('utf-8',{fatal:true}).decode(raw);}catch{}}out.push(C.indexLocal(path,source,file.size));if(i%10===0){$('load-info').textContent=(i+1)+' / '+files.length+' 파일 · 기기 밖으로 전송하지 않습니다';await new Promise(r=>setTimeout(r,0));}}
 if(!out.length)throw Error('표시할 파일이 없습니다.');const next={schema:1,repo:name,commit:'local-worktree',commitDate:'',worktree:true,files:out,metrics:C.metrics(out),symbolMethod:'Declaration patterns; not a compiler AST.'};initData(next);toast(out.length+'개 로컬 파일을 열었습니다.'+(ignored?' 생성물·의존성 '+ignored+'개 제외.':''));}catch(e){toast('폴더 열기 실패: '+e.message);}finally{$('loading').hidden=true;$('folder-input').value='';}}
function bindUI(){
 const on=(id,fn,type='click')=>$(id).addEventListener(type,fn);
 const home=()=>{stopTour();selectNode(tree.root);view.focus(tree.root);};on('brand',home);on('home-btn',home);
 on('focus-btn',()=>view.focus(selectedPage||selected,!!selectedPage));on('zoom-in',()=>view.zoom(.74));on('zoom-out',()=>view.zoom(1/.74));
 on('view-3d',()=>{stopTour();view.setMode('3d');});on('view-2d',()=>{stopTour();view.setMode('2d');});
 on('metric',()=>{stopTour();selectedPage=null;layout=C.layout(tree,$('metric').value);view.rebuild();view.focus(selected||tree.root);renderInspector();},'change');
 on('color-mode',()=>{view.colorMode=$('color-mode').value;view.rebuild();renderLegend();},'change');
 on('height',()=>{view.height=+$('height').value/100;view.rebuild();},'input');
 on('labels-btn',()=>{view.labels=!view.labels;view.dirty=true;$('labels-btn').classList.toggle('active',view.labels);$('labels-btn').setAttribute('aria-pressed',view.labels);});
 on('explorer-toggle',()=>{document.body.classList.toggle(innerWidth<=1020?'mobile-explorer':'no-explorer');view.resize();});
 on('inspector-toggle',()=>{document.body.classList.toggle(innerWidth<=760?'mobile-inspector':'no-inspector');view.resize();});
 const zen=()=>{document.body.classList.toggle('zen');$('exit-zen').hidden=!document.body.classList.contains('zen');view.resize();};on('zen-btn',zen);on('exit-zen',zen);
 on('tree-filter',renderTree,'input');on('collapse-tree',()=>{expanded.clear();expanded.add('');renderTree();});
 on('tree',e=>{const b=e.target.closest('[data-tree]');if(!b)return;const n=tree.map.get(b.dataset.tree);if(!n)return;if(!n.file){if(expanded.has(n.path))expanded.delete(n.path);else expanded.add(n.path);}selectNode(n);view.focus(n);});
 on('breadcrumbs',e=>{const b=e.target.closest('[data-path]');if(b){const n=tree.map.get(b.dataset.path);if(n){selectNode(n);view.focus(n);}}});
 on('inspector-body',e=>{let b=e.target.closest('[data-file]');if(b){const f=data.files[+b.dataset.file];selectNode(f.node);view.focus(f.node);return;}b=e.target.closest('[data-open-source]');if(b){const f=data.files[+b.dataset.openSource];openEditor(f,selectedPage?.section.start||1);return;}b=e.target.closest('[data-symbol]');if(b&&selected?.file){const f=selected.file,n=+b.dataset.symbol;openEditor(f,n);const pg=layout.pages.find(p=>p.file===f&&p.section.start<=n&&p.section.end>=n);if(pg)view.focus(pg,true);}});
 on('editor-tabs',e=>{const b=e.target.closest('[data-tab]');if(b)openEditor(data.files[+b.dataset.tab]);});on('close-editor',closeEditor);on('source-scroll',renderSource,'scroll');on('go-line',jumpSource);on('line-input',e=>{if(e.key==='Enter')jumpSource();},'keydown');
 on('download-source',()=>{if(editorFile)saveBlob(new Blob([editorFile.source],{type:'text/plain;charset=utf-8'}),editorFile.path.split('/').pop());});
 on('copy-source',async()=>{if(!editorFile)return;try{if(navigator.clipboard?.writeText)await navigator.clipboard.writeText(editorFile.source);else throw Error();toast('원본 소스 전체를 복사했습니다.');}catch{const ta=document.createElement('textarea');ta.value=editorFile.source;ta.style.position='fixed';ta.style.opacity='0';document.body.append(ta);ta.select();const ok=document.execCommand('copy');ta.remove();toast(ok?'원본 소스 전체를 복사했습니다.':'클립보드 권한이 없습니다. 저장 버튼으로 원본을 저장하세요.');}});
 on('expand-editor',()=>{$('editor').style.height=$('editor').style.height==='80%'?'360px':'80%';setTimeout(renderSource,0);});
 let resize=null;on('editor-resize',e=>{resize={y:e.clientY,height:$('editor').getBoundingClientRect().height};$('editor-resize').setPointerCapture(e.pointerId);},'pointerdown');on('editor-resize',e=>{if(resize){$('editor').style.height=Math.max(160,Math.min($('workspace').clientHeight*.9,resize.height+resize.y-e.clientY))+'px';renderSource();}},'pointermove');on('editor-resize',()=>resize=null,'pointerup');on('editor-resize',()=>resize=null,'pointercancel');
 on('global-search',()=>openSearch());on('search-close',()=>$('search-dialog').close());document.querySelectorAll('.search-tabs button').forEach(b=>b.addEventListener('click',()=>{searchMode=b.dataset.mode;updateSearchTabs();doSearch();$('search-input').focus();}));
 on('search-input',()=>{clearTimeout(searchTimer);searchTimer=setTimeout(doSearch,100);},'input');
 on('search-results',e=>{const b=e.target.closest('[data-result]');if(b)chooseSearch(+b.dataset.result);});
 on('search-input',e=>{if(e.key==='Enter'){e.preventDefault();clearTimeout(searchTimer);chooseSearch(searchIndex);}if(['ArrowDown','ArrowUp'].includes(e.key)){e.preventDefault();searchIndex=Math.max(0,Math.min(searchResult.length-1,searchIndex+(e.key==='ArrowDown'?1:-1)));document.querySelectorAll('.search-result').forEach((b,i)=>{b.classList.toggle('chosen',i===searchIndex);b.setAttribute('aria-selected',i===searchIndex);});$('search-results').querySelector('.chosen')?.scrollIntoView({block:'nearest'});}},'keydown');
 on('help-btn',()=>$('help-dialog').showModal());on('about-btn',()=>$('about-dialog').showModal());document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}}));
 on('tour-btn',startTour);on('capture-btn',capture);on('record-btn',record);on('export-btn',exportHTML);on('import-btn',()=>$('folder-input').click());on('folder-input',()=>importFolder($('folder-input').files),'change');
 on('dismiss-fallback',()=>$('gl-fallback').hidden=true);
 on('minimap',e=>{stopTour();const r=$('minimap').getBoundingClientRect(),x=(e.clientX-r.left)/r.width,z=(e.clientY-r.top)/r.height;const xx=(x-.5)*layout.width,zz=(z-.5)*layout.depth;if(view.fallback){view.flat.x=xx;view.flat.z=zz;}else{const delta=new T.Vector3(xx-view.controls.target.x,0,zz-view.controls.target.z);view.controls.target.add(delta);view.camera.position.add(delta);view.anim=null;view.controls.update();}view.dirty=true;});
 window.addEventListener('keydown',e=>{
  const key=e.key.toLowerCase(),typing=['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName),dialog=!!document.querySelector('dialog[open]');
  if((e.ctrlKey||e.metaKey)&&['k','p'].includes(key)){e.preventDefault();if(!$('search-dialog').open)openSearch('files');return;}
  if((e.ctrlKey||e.metaKey)&&e.shiftKey&&key==='f'){e.preventDefault();if(!$('search-dialog').open)openSearch('text');return;}
  if(key==='escape'&&!dialog){stopTour();if(!$('editor').hidden)closeEditor();else if(document.body.classList.contains('zen'))zen();else if(document.body.classList.contains('mobile-inspector')||document.body.classList.contains('mobile-explorer'))document.body.classList.remove('mobile-inspector','mobile-explorer');else if(selectedPage){selectedPage=null;view.focus(selected);view.updateSelection();}else home();return;}
  if(typing||dialog||e.ctrlKey||e.metaKey||e.altKey)return;
  if(key==='h')home();else if(key==='f')view.focus(selectedPage||selected,!!selectedPage);else if(key==='v')view.setMode(view.mode==='3d'?'2d':'3d');else if(key==='l')$('labels-btn').click();else if(key==='z')zen();else if(key==='?')$('help-dialog').showModal();else if(key==='/'){e.preventDefault();$('tree-filter').focus();}else if(key===' '){e.preventDefault();startTour();}else if(key==='enter'&&selected?.file){e.preventDefault();openEditor(selected.file,selectedPage?.section.start||1);}else if(key==='+'||key==='=')view.zoom(.75);else if(key==='-')view.zoom(1/.75);
 });
}
let frames=0,lastFps=performance.now();
function animate(now){requestAnimationFrame(animate);if(document.hidden)return;tickTour(now);const rendered=view.tick(now);if(recordingCanvas){composite(recordingCanvas);const secs=Math.floor((now-recordStart)/1000);$('record-btn').title='녹화 종료 · '+secs+'초';if(secs>=120&&recorder?.state==='recording')recorder.stop();}if(rendered)frames++;if(now-lastFps>=1000){$('fps').textContent=frames?Math.round(frames*1000/(now-lastFps))+' fps':'idle';frames=0;lastFps=now;$('lod-status').textContent=view.activeTextures?'LOD 3 · 원문 '+view.activeTextures+' pages':'LOD '+(view.camera&&view.camera.position.distanceTo(view.controls.target)<90?'2 · 소스 페이지':'1 · 파일 지도');$('draw-status').textContent=view.fallback?'Canvas 2D':view.renderer.info.render.calls+' draws';}}
function bootstrap(){try{initData(data);view=new Landscape();view.rebuild();view.focus(tree.root);renderLegend();bindUI();$('loading').hidden=true;window.__scope={get data(){return data;},get tree(){return tree;},get layout(){return layout;},get selected(){return selected;},get selectedPage(){return selectedPage;},get editorFile(){return editorFile;},get view(){return view;},selectPath(path){const n=tree.map.get(path);if(n){selectNode(n);view.focus(n);}return !!n;},openPath(path,line=1){const f=tree.map.get(path)?.file;if(f)openEditor(f,line);},focusPage(path,line=1){const f=tree.map.get(path)?.file,p=layout.pages.find(p=>p.file===f&&p.section.start<=line&&p.section.end>=line);if(p){selectNode(f.node,p);view.focus(p,true);}return !!p;},search:(q,m)=>C.search(data.files,q,m),importFolder,exportHTML,capture,get sourceText(){return editorFile?.source;},get tour(){return !!tour;}};requestAnimationFrame(animate);}catch(e){console.error(e);$('loading').innerHTML='<div class="load-mark">!</div><strong>지도를 열지 못했습니다.</strong><p>'+esc(e.message)+'</p><small>다운로드한 HTML을 최신 데스크톱 브라우저에서 다시 여세요.</small>';}}
setTimeout(bootstrap,25);
})();
